* src/modules/Makefile.am (sd_flite_LDFLAGS): Use $(flite_basic) and $(flite_kal) from configure.in.
* configure.in: If flite_cmu_us_kal16 is available, compile against this better voice,
otherwise compile against flite_cmu_us_kal.

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -30,18 +30,31 @@ AC_CHECK_LIB(pthread,
 
 dnl Check for Flite (currently required)
 AC_CHECK_LIB(flite,
-        flite_init,,
-        echo "*** Required Flite libraries missing or instalation incomplete! See INSTALL .";exit 1)
-AC_CHECK_LIB(flite_cmulex,
-        cmu_lex_init,,
-        echo "*** Required Flite libraries missing or instalation incomplete! See INSTALL .";exit 1)
-AC_CHECK_LIB(flite_usenglish,
-        usenglish_init,,
+        flite_init, echo "",
         echo "*** Required Flite libraries missing or instalation incomplete! See INSTALL .";exit 1)
 
+AC_CHECK_LIB(flite_cmulex,
+        cmu_lex_init, echo "",
+        echo "*** Required Flite libraries missing or instalation incomplete! See INSTALL .";exit 1,
+	-lflite)
+
+AC_CHECK_LIB(flite_usenglish,
+        usenglish_init, echo "",
+        echo "*** Required Flite libraries missing or instalation incomplete! See INSTALL .";exit 1,
+	-lflite)
+
+flite_basic="-lflite -lflite_cmulex -lflite_usenglish";
+
 AC_CHECK_LIB(flite_cmu_us_kal16,
-        register_cmu_us_kal,, 
-        echo "*** Required Flite libraries missing or instalation incomplete! See INSTALL .";exit 1) 
+        register_cmu_us_kal, flite_kal="-lflite_cmu_us_kal16", 
+        	AC_CHECK_LIB(flite_cmu_us_kal,	
+        	register_cmu_us_kal, flite_libs="-lflite_cmu_us_kal", 
+        	echo "*** Required Flite kal voice library missing or instalation incomplete! See INSTALL .";exit 1,
+		-lflite -lflite_usenglish -lflite_cmulex),
+	-lflite -lflite_usenglish -lflite_cmulex)
+
+AC_SUBST(flite_basic)
+AC_SUBST(flite_kal)
 
 glib_include=`pkg-config --cflags glib-2.0`
 AC_SUBST(glib_include)
