PulseAudio support (initial release)

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -190,6 +190,25 @@ AC_ARG_WITH(alsa, AS_HELP_STRING(--with-alsa, Compile with ALSA support),
 
 AM_CONDITIONAL(alsa_support, test $alsa_aud = "true")
 
+AC_CHECK_LIB(pulse,
+        pa_threaded_mainloop_new,
+	pulse_aud="true";echo "Compiling with PulseAudio support.";,
+        pulse_aud="false";echo "*** PulseAudio library missing. Compiling without PulseAudio support! See INSTALL.";,
+	-lpulse)
+
+AC_ARG_WITH(pulse, AS_HELP_STRING(--with-pulse, Compile with PulseAudio support),
+		 if test $withval = "no"; then 
+		    echo "Forced compilation without PulseAudio support.";
+		    pulse_aud="false";
+		 else 
+		    if test $pulse_aud = "false"; then
+		       echo "PulseAudio support is not available. Sorry."; exit 1;
+		    fi
+                 fi
+ 		 echo "")
+
+AM_CONDITIONAL(pulse_support, test $pulse_aud = "true")
+
 glib_include=`pkg-config --cflags glib-2.0`
 AC_SUBST(glib_include)
 glib_libs=`pkg-config --libs glib-2.0`
