Complain if some of the libraries isn't present and exit the build process. (AC_LANG): Now set to C. (AC_OUTPUT): Inserted doc/Makefile

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -1,6 +1,8 @@
 dnl Process this file with autoconf to produce a configure script.
 AC_INIT(configure.in)
 
+AC_LANG(C)
+
 dnl progs
 AC_PROG_CC
 
@@ -10,16 +12,39 @@ AM_INIT_AUTOMAKE(speechd, "`cat version.sh|grep '^VERSION'|awk -F= '{print $2}'`
 AM_CONFIG_HEADER(config.h)
 
 dnl Checks for libraries.
-AC_CHECK_LIB(dl, main)
-AC_CHECK_LIB(dotconf, main)
-AC_CHECK_LIB(glib-2.0, main)
-AC_CHECK_LIB(ncurses, main)
-AC_CHECK_LIB(pthread, pthread_create)
-AC_CHECK_LIB(flite, flite_init)
-AC_CHECK_LIB(flite_cmu_us_kal, register_cmu_us_kal)
-AC_CHECK_LIB(flite_usenglish, usenglish_init)
-AC_CHECK_LIB(flite_cmulex, cmu_lex_init)
-AC_CHECK_LIB(recode, main)
+AC_CHECK_LIB(m,
+        sqrt,,
+        echo "*** Required math library missing! See INSTALL .";exit 1)
+AC_CHECK_LIB(dl,
+        main,,
+        echo "*** Required dl library missing! See INSTALL .";exit 1)
+AC_CHECK_LIB(dotconf,
+        main,,
+        echo "*** Required DotConf library missing! See INSTALL .";exit 1)
+AC_CHECK_LIB(glib-2.0,
+        g_list_append,,
+        echo "*** Required Glib-2.0 library missing! See INSTALL .";exit 1)
+AC_CHECK_LIB(pthread,
+        pthread_create,,
+        echo "*** Required pthread library missing! See INSTALL .";exit 1)
+
+dnl Check for Flite (currently required)
+AC_CHECK_LIB(flite,
+        flite_init,,
+        echo "*** Required Flite libraries missing or instalation incomplete! See INSTALL .";exit 1)
+AC_CHECK_LIB(flite_cmulex,
+        cmu_lex_init,,
+        echo "*** Required Flite libraries missing or instalation incomplete! See INSTALL .";exit 1)
+AC_CHECK_LIB(flite_usenglish,
+        usenglish_init,,
+        echo "*** Required Flite libraries missing or instalation incomplete! See INSTALL .";exit 1)
+AC_CHECK_LIB(flite_cmu_us_kal,
+        register_cmu_us_kal,, 
+        echo "*** Required Flite libraries missing or instalation incomplete! See INSTALL .";exit 1) 
+
+AC_CHECK_LIB(recode,
+        recode_string,,
+        echo "*** Required Recode library missing! See INSTALL .";exit 1)
 
 glib_include=`pkg-config --cflags glib-2.0`
 AC_SUBST(glib_include)
@@ -49,5 +74,5 @@ AC_PROG_MAKE_SET
 
 AM_PROG_LIBTOOL
 
-AC_OUTPUT([Makefile src/Makefile src/server/Makefile src/modules/Makefile src/c/Makefile src/c/api/Makefile src/c/clients/Makefile src/c/clients/say/Makefile src/tests/Makefile src/audio/Makefile config/Makefile config/en/Makefile sounds/Makefile])
+AC_OUTPUT([Makefile src/Makefile src/server/Makefile src/modules/Makefile src/c/Makefile src/c/api/Makefile src/c/clients/Makefile src/c/clients/say/Makefile src/tests/Makefile src/audio/Makefile config/Makefile config/en/Makefile sounds/Makefile doc/Makefile])
 
