audio - Add libao output support
Add support for using the libao audio library as an audio output choice.
While libao also supports the same output methods that speech-dispatcher
supports, libao is a well tested, and reliable library for audio output. Thanks
to Marco Skambraks <marco@openblinux.de> for the patch.

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -203,6 +203,25 @@ AC_ARG_WITH(nas, AS_HELP_STRING(--with-nas, Compile with Network Audio System (N
 
 AM_CONDITIONAL(nas_support, test $nas_aud = "true")
 
+AC_CHECK_LIB(ao,
+        ao_play,
+	libao_aud="true";echo "Compiling with libao support.";,
+        libao_aud="false";echo "*** libao library missing. Compiling without libao support! See INSTALL.";)
+
+AC_ARG_WITH(libao, AS_HELP_STRING(--with-libao, Compile with libao support),
+		 if test $withval = "no"; then 
+		    echo "Forced compilation without libao support.";
+		    libao_aud="false";
+		 else 
+		    if test $libao_aud = "false"; then
+		       echo "libao support is not available. Sorry."; exit 1;
+		    fi
+                 fi
+ 		 echo "")
+
+AM_CONDITIONAL(libao_support, test $libao_aud = "true")
+
+
 AC_CHECK_LIB(asound,
         snd_pcm_open,
 	alsa_aud="true";echo "Compiling with ALSA support.";,
