*** empty log message ***

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -13,37 +13,38 @@ AM_CONFIG_HEADER(config.h)
 
 dnl Checks for libraries.
 AC_CHECK_LIB(m,
-        sqrt,,
+        sqrt, echo "",
         echo "*** Required math library missing! See INSTALL .";exit 1)
 AC_CHECK_LIB(dl,
-        main,,
+        main, echo "",
         echo "*** Required dl library missing! See INSTALL .";exit 1)
 AC_CHECK_LIB(dotconf,
-        main,,
+        main, echo "",
         echo "*** Required DotConf library missing! See INSTALL .";exit 1)
 AC_CHECK_LIB(glib-2.0,
-        g_list_append,,
+        g_list_append, echo "",
         echo "*** Required Glib-2.0 library missing! See INSTALL .";exit 1)
 AC_CHECK_LIB(pthread,
-        pthread_create,,
+        pthread_create, echo "",
         echo "*** Required pthread library missing! See INSTALL .";exit 1)
 
 dnl Check for Flite (currently required)
 AC_CHECK_LIB(flite,
         flite_init, echo "",
-        echo "*** Required Flite libraries missing or instalation incomplete! See INSTALL .";exit 1)
+        echo "*** Required Flite libraries missing or instalation incomplete! See INSTALL .";exit 1,
+	-lm)
 
 AC_CHECK_LIB(flite_cmulex,
         cmu_lex_init, echo "",
         echo "*** Required Flite libraries missing or instalation incomplete! See INSTALL .";exit 1,
-	-lflite)
+	-lflite -lm)
 
 AC_CHECK_LIB(flite_usenglish,
         usenglish_init, echo "",
         echo "*** Required Flite libraries missing or instalation incomplete! See INSTALL .";exit 1,
-	-lflite)
+	-lflite -lm)
 
-flite_basic="-lflite -lflite_cmulex -lflite_usenglish";
+flite_basic="-lm -lflite -lflite_cmulex -lflite_usenglish";
 
 AC_CHECK_LIB(flite_cmu_us_kal16,
         register_cmu_us_kal, flite_kal="-lflite_cmu_us_kal16", 
@@ -51,7 +52,7 @@ AC_CHECK_LIB(flite_cmu_us_kal16,
         	register_cmu_us_kal, flite_libs="-lflite_cmu_us_kal", 
         	echo "*** Required Flite kal voice library missing or instalation incomplete! See INSTALL .";exit 1,
 		-lflite -lflite_usenglish -lflite_cmulex),
-	-lflite -lflite_usenglish -lflite_cmulex)
+	-lm -lflite -lflite_usenglish -lflite_cmulex)
 
 AC_SUBST(flite_basic)
 AC_SUBST(flite_kal)
