locale: Import mathematic symbols from Orca
Refs #1038

diff --git a/locale/import-orca b/locale/import-orca
--- a/locale/import-orca
+++ b/locale/import-orca
@@ -1,7 +1,7 @@
 #!/bin/bash
 # coding: utf-8
 # Orca symbols import
-# Copyright (C) 2020-2024 Samuel Thibault <samuel.thibault@ens-lyon.org>
+# Copyright (C) 2020-2025 Samuel Thibault <samuel.thibault@ens-lyon.org>
 #
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU Lesser General Public License as published by
@@ -18,84 +18,21 @@
 
 export TEXTDOMAINDIR=/usr/local/share/locale
 
-num=$1
+translation=`LANGUAGE="$lang" gettext -d orca "math symbol" "up arrow"`
+if [ -z "$translation" ]; then
+    echo "Missing orca translations in $TEXTDOMAINDIR"
+    exit 1
+fi
+
+num=-math
 
 LANG=C python3 > orca$num.autosym << EOF
-from orca.chnames import chnames
-from orca.punctuation_settings import punctuation, LEVEL_ALL, LEVEL_MOST, LEVEL_SOME, LEVEL_NONE, PUNCTUATION_REPLACE, PUNCTUATION_INSERT
+from orca.mathsymbols import _arrows
+from orca.mathsymbols import _operators
+from orca.mathsymbols import _shapes
 
-LEVEL_CHAR = -1
-l = {
-  LEVEL_CHAR: 'char',
-  LEVEL_ALL: 'all',
-  LEVEL_MOST: 'most',
-  LEVEL_SOME: 'some',
-  LEVEL_NONE: 'none',
-}
-
-mypunctuation = {
-  ' ': [ LEVEL_CHAR, PUNCTUATION_REPLACE ],
-  '\\n': [ LEVEL_CHAR, PUNCTUATION_REPLACE ],
-  '\\t': [ LEVEL_CHAR, PUNCTUATION_REPLACE ],
-  '\\\\': [ LEVEL_MOST, PUNCTUATION_REPLACE ],
-  '\\u00a0': [ LEVEL_CHAR, PUNCTUATION_REPLACE ],
-  '\\u00a1': [ LEVEL_SOME, PUNCTUATION_REPLACE ],
-  '\\u00a4': [ LEVEL_ALL, PUNCTUATION_REPLACE ],
-  '\\u00a6': [ LEVEL_MOST, PUNCTUATION_REPLACE ],
-  '\\u00a8': [ LEVEL_MOST, PUNCTUATION_REPLACE ],
-  '\\u00aa': [ LEVEL_SOME, PUNCTUATION_REPLACE ],
-  '\\u00ad': [ LEVEL_MOST, PUNCTUATION_REPLACE ],
-  '\\u00af': [ LEVEL_MOST, PUNCTUATION_REPLACE ],
-  '\\u00b4': [ LEVEL_MOST, PUNCTUATION_REPLACE ],
-  '\\u00b5': [ LEVEL_SOME, PUNCTUATION_REPLACE ],
-  '\\u00b6': [ LEVEL_MOST, PUNCTUATION_REPLACE ],
-  '\\u00b8': [ LEVEL_MOST, PUNCTUATION_REPLACE ],
-  '\\u00ba': [ LEVEL_SOME, PUNCTUATION_REPLACE ],
-  '\\u00bf': [ LEVEL_SOME, PUNCTUATION_REPLACE ],
-  '\\u0192': [ LEVEL_ALL, PUNCTUATION_REPLACE ],
-  '\\u2034': [ LEVEL_SOME, PUNCTUATION_REPLACE ],
-  '\\ufffc': [ LEVEL_NONE, PUNCTUATION_REPLACE ],
-}
-
-for sym,name in chnames.items():
-    c = ord(sym[0])
-    if ('$num' != '-chars') == \
-        (c >= 0xc0 and c <= 0xff
-         or c == 0x178
-         or c == 0xe00a
-         or c == 0xe00c):
-        continue
-
-    level = 'none'
-    keep = ''
-
-    if sym in punctuation:
-        level, flag = punctuation[sym]
-    elif sym in mypunctuation:
-        level, flag = mypunctuation[sym]
-    else:
-        print("# %s not in punctuation" % sym)
-        if '$num' == '-chars':
-            level, flag = LEVEL_CHAR, PUNCTUATION_REPLACE
-            keep = '\tnorep'
-        else:
-            level, flag = LEVEL_NONE, PUNCTUATION_REPLACE
-
-    if flag == PUNCTUATION_INSERT:
-        keep = '\talways'
-    if level not in l:
-        print("oops, %s not in l!?" % level)
-
-    if sym == '\\t':
-        sym = "\\\\t"
-    elif sym == '\\n':
-        sym = "\\\\n"
-    elif sym == '\\\\':
-        sym = "\\\\\\\\"
-    elif sym == '#':
-        sym = "\\\\#"
-
-    print("%s\\t%s\\t%s%s" % (sym, name, l[level], keep))
+for sym,name in (_arrows|_operators|_shapes).items():
+    print("%s\\tmath symbol %s\\t%s%s" % (sym, name, 'none', ''))
 EOF
 
 for lang in base $(cat orca.polist)
@@ -108,7 +45,7 @@ do
 # DO NOT MODIFY IT!
 # See locale/README.md to know how to import dictionaries
 
-# locale/$lang/orca.dic
+# locale/$lang/orca$num.dic
 # Copyright (C) 2004-2020 Free Software Foundation, Inc.
 # This file is distributed under the same license as the orca package.
 
@@ -130,6 +67,9 @@ EOF
 					C_version=${C_version#math symbol }
 					;;
 			esac
+			case "$C_version" in
+				'') continue ;;
+			esac
 
 			sym="${sym//\\/\\\\}"
 			sym="${sym//[/\\[}"
@@ -138,9 +78,14 @@ EOF
 				keep=$'\t'"$keep"
 			fi
 
-			if ! grep "^$sym	" $lang/symbols.dic > /dev/null 2>&1
+			if ! grep "^$sym	" $lang/symbols.dic > /dev/null 2>&1 \
+			&& ! grep "^$sym	" $lang/emojis.dic  > /dev/null 2>&1
 			then
-				translation=`LANGUAGE="$lang" gettext -d orca $CTX "$C_version"`
+				if [ -n "$CTX" ] ; then
+				    translation=`LANGUAGE="$lang" gettext -d orca "$CTX" "$C_version"`
+				else
+				    translation=`LANGUAGE="$lang" gettext -d orca "$C_version"`
+				fi
 
 				if [ "$lang" == base -o "$translation" != "$C_version" ]
 				then
